services:
  website:
    build: .
    image: asianwork
    restart: always
    container_name: asianwork
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.asianwork.rule=Host(`${HOST}`)"
      - "traefik.http.routers.asianwork.entrypoints=websecure"
      - "traefik.http.routers.asianwork.tls.certresolver=myresolver"
      - "traefik.http.services.asianwork.loadbalancer.server.port=3914"

    networks:
      - traefik_network

networks:
  traefik_network:
    external: true
